/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */

package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class Member (
  username: String,
  cardnumber: Option[String],
  address: Option[String],
  status: Option[MemberEnums.Status]
) extends ApiModel

object MemberEnums {

  type Status = Status.Value
  object Status extends Enumeration {
    val Active = Value("active")
    val Suspend = Value("suspend")
    val Cancel = Value("cancel")
    val Expire = Value("expire")
  }

}

